#!/bin/sh

#
# see colors:
#

BLACK='[30m'
RED='[31m'
GREEN='[32m'
YELLOW='[33m'
BLUE='[34m'
MAGNETA='[35m'
CYAN='[36m'
WHITE='[37m'

BGBLACK='[40m'
BGRED='[41m'
BGGREEN='[42m'
BGYELLOW='[43m'
BGBLUE='[44m'
BGMAGNETA='[45m'
BGCYAN='[46m'
BGWHITE='[47m'

BRIGHT='[01m'
NORMAL='[00m'

UNDERSCORE='[04m'  # only works in xterms
BLINK='[05m'       # doesn't work in xterms
REVERSE='[07m'




echo $NORMAL'BLACK:  ' $BLACK   'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'WHITE:  ' $WHITE   'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'RED:    ' $RED     'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'GREEN:  ' $GREEN   'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'YELLOW: ' $YELLOW  'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'BLUE:   ' $BLUE    'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'MAGNETA:' $MAGNETA 'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'CYAN:   ' $CYAN    'NORMAL' $BRIGHT 'BRIGHT'



echo $NORMAL'BLACK:  ' $REVERSE$BLACK   'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'WHITE:  ' $REVERSE$WHITE   'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'RED:    ' $REVERSE$RED     'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'GREEN:  ' $REVERSE$GREEN   'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'YELLOW: ' $REVERSE$YELLOW  'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'BLUE:   ' $REVERSE$BLUE    'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'MAGNETA:' $REVERSE$MAGNETA 'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'CYAN:   ' $REVERSE$CYAN    'NORMAL' $BRIGHT 'BRIGHT'


echo $NORMAL'BLACK:  ' $UNDERSCORE$BLACK   'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'WHITE:  ' $UNDERSCORE$WHITE   'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'RED:    ' $UNDERSCORE$RED     'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'GREEN:  ' $UNDERSCORE$GREEN   'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'YELLOW: ' $UNDERSCORE$YELLOW  'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'BLUE:   ' $UNDERSCORE$BLUE    'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'MAGNETA:' $UNDERSCORE$MAGNETA 'NORMAL' $BRIGHT 'BRIGHT'
echo $NORMAL'CYAN:   ' $UNDERSCORE$CYAN    'NORMAL' $BRIGHT 'BRIGHT'


echo $BGRED$BLACK ' VOODOO '  $NORMAL
echo $BGRED$BLUE ' VOODOO '  $NORMAL
echo $BLINK$BGRED$GREEN ' VOODOO '  $NORMAL

echo $NORMAL

